#!/bin/bash
source /opt/ros/humble/setup.bash
VERSION=$(git describe --tags --long).$(TZ="Asia/Shanghai" date +"%Y%m%d.%H%M%S").$( lsb_release -c | awk '{print $2}')
VERSION=$(echo ${VERSION} | tr _ -)
dch -b -v ${VERSION} $(git log -n 1 --pretty=format:"%s")
echo "VERSION is ${VERSION}"
if [ ! -f "debian/links" ]; then
  pkg=$(head -n 1 debian/changelog | grep ros-humble | awk '{print $1}')
  if [ "$pkg" ]; then
    echo this is a ros package and name is $pkg
    echo "/etc/ros/dds/service-environment.conf /lib/systemd/system/${pkg}.service.d/00-service-environment.conf" > debian/links
  fi
fi
DEB_BUILD_OPTIONS=parallel=15 fakeroot debian/rules binary
git restore debian/changelog

