[Unit]
After=network.target
Requires=systemd-networkd.service
After=systemd-networkd.service

[Service]
Environment=ROS_HOME=/root/.ros
Environment=ROS_DISTRO=humble
Environment=ROS_LOCALHOST_ONLY=0
Environment=ROS_PYTHON_VERSION=3
Environment=ROS_VERSION=2
Environment=PYTHONPATH=/opt/ros/humble/lib/python3.8/site-packages:/opt/ros/humble/lib/python3.10/site-packages:/opt/ros/humble/local/lib/python3.10/dist-packages
Environment=AMENT_PREFIX_PATH=/opt/ros/humble
Environment=PATH=/opt/ros/humble/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=LD_LIBRARY_PATH=/opt/ros/humble/opt/rviz_ogre_vendor/lib:/opt/ros/humble/lib/aarch64-linux-gnu:/opt/ros/humble/lib:/usr/local/lib/:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/opt/openvdb_vendor/lib
Environment=RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
Environment=CYCLONEDDS_URI=file:///etc/ros/dds/cyclonedds.xml
Environment=ROS_LOG_DIR=/tmp/ros
# Enable coredump
LimitCORE=infinity
Environment=ROS_DOMAIN_ID=101

Environment=ROS2_SYSTEMD_LOG_ENABLE=true
Environment=SPDLOG_STDOUT=false
Environment=SPDLOG_SYSTEMD=true
Environment=SPDLOG_LEVEL=info
Environment=RCUTILS_CONSOLE_OUTPUT_FORMAT="[{severity}] [{name}]:{message}"
StandardError=null
StandardOutput=null
